# 1 "data/maps/ShoalCave_LowTideIceRoom/scripts.pory"

# 2 "data/maps/ShoalCave_LowTideIceRoom/scripts.pory"
ShoalCave_LowTideIceRoom_MapScripts:: @ 82396A1
# 3 "data/maps/ShoalCave_LowTideIceRoom/scripts.pory"
	map_script MAP_SCRIPT_ON_LOAD, ShoalCave_LowTideIceRoom_OnLoad
# 4 "data/maps/ShoalCave_LowTideIceRoom/scripts.pory"
	.byte 0
# 5 "data/maps/ShoalCave_LowTideIceRoom/scripts.pory"
	
# 6 "data/maps/ShoalCave_LowTideIceRoom/scripts.pory"
ShoalCave_LowTideIceRoom_OnLoad: @ 8236F16
# 7 "data/maps/ShoalCave_LowTideIceRoom/scripts.pory"
	end
