# 1 "data/maps/BattleFrontier_Lounge8/scripts.pory"

# 2 "data/maps/BattleFrontier_Lounge8/scripts.pory"
BattleFrontier_Lounge8_MapScripts:: @ 82676C9
# 3 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.byte 0
# 4 "data/maps/BattleFrontier_Lounge8/scripts.pory"

# 5 "data/maps/BattleFrontier_Lounge8/scripts.pory"
BattleFrontier_Lounge8_EventScript_Man:: @ 82676CA
# 6 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	msgbox BattleFrontier_Lounge8_Text_WhatATrainerNeeds, MSGBOX_NPC
# 7 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	end
# 8 "data/maps/BattleFrontier_Lounge8/scripts.pory"

# 9 "data/maps/BattleFrontier_Lounge8/scripts.pory"
BattleFrontier_Lounge8_EventScript_Woman:: @ 82676D3
# 10 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	msgbox BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains, MSGBOX_NPC
# 11 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	end
# 12 "data/maps/BattleFrontier_Lounge8/scripts.pory"

# 13 "data/maps/BattleFrontier_Lounge8/scripts.pory"
BattleFrontier_Lounge8_EventScript_NinjaBoy:: @ 82676DC
# 14 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	msgbox BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling, MSGBOX_NPC
# 15 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	end
# 16 "data/maps/BattleFrontier_Lounge8/scripts.pory"

# 17 "data/maps/BattleFrontier_Lounge8/scripts.pory"
BattleFrontier_Lounge8_Text_WhatATrainerNeeds: @ 82676E5
# 18 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "What a Trainer needs…\p"
# 19 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "Knowledge…\n"
# 20 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "Strategy…\l"
# 21 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "Luck…\l"
# 22 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "Guts…\l"
# 23 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "Spirit…\l"
# 24 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "Bravery…\l"
# 25 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "And ability…\p"
# 26 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "Well, I'm all set in every way!\n"
# 27 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "I'll be unstoppable at every building!\p"
# 28 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "Huh? Pokémon?\n"
# 29 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "What's that?$"
# 30 "data/maps/BattleFrontier_Lounge8/scripts.pory"

# 31 "data/maps/BattleFrontier_Lounge8/scripts.pory"
BattleFrontier_Lounge8_Text_KnowAboutFrontierBrains: @ 826779C
# 32 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "Do you know about the Frontier\n"
# 33 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "Brains?\p"
# 34 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "That's what Scott calls the seven\n"
# 35 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "special Trainers that run the seven\l"
# 36 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "facilities in the Battle Frontier.$"
# 37 "data/maps/BattleFrontier_Lounge8/scripts.pory"

# 38 "data/maps/BattleFrontier_Lounge8/scripts.pory"
BattleFrontier_Lounge8_Text_ToldMeIHaveTalentForBattling: @ 826782C
# 39 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "At the Battle Tower, an older girl\n"
# 40 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "told me that I have a lot of talent\l"
# 41 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "for battling!\p"
# 42 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "I like Pokémon Contests more!\p"
# 43 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "But I'm no good at Contests!\p"
# 44 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "I guess having talent and liking\n"
# 45 "data/maps/BattleFrontier_Lounge8/scripts.pory"
	.string "something aren't the same.$"
