# 1 "data/maps/BattleFrontier_Lounge4/scripts.pory"

# 2 "data/maps/BattleFrontier_Lounge4/scripts.pory"
BattleFrontier_Lounge4_MapScripts:: @ 826358C
# 3 "data/maps/BattleFrontier_Lounge4/scripts.pory"
	.byte 0
# 4 "data/maps/BattleFrontier_Lounge4/scripts.pory"

# 5 "data/maps/BattleFrontier_Lounge4/scripts.pory"
BattleFrontier_Lounge4_EventScript_Woman:: @ 826358D
# 6 "data/maps/BattleFrontier_Lounge4/scripts.pory"
	msgbox BattleFrontier_Lounge4_Text_WonderIfInterviewsAiring, MSGBOX_NPC
# 7 "data/maps/BattleFrontier_Lounge4/scripts.pory"
	end
# 8 "data/maps/BattleFrontier_Lounge4/scripts.pory"

# 9 "data/maps/BattleFrontier_Lounge4/scripts.pory"
BattleFrontier_Lounge4_EventScript_Cook:: @ 8263596
# 10 "data/maps/BattleFrontier_Lounge4/scripts.pory"
	msgbox BattleFrontier_Lounge4_Text_IfIOpenedRestaurantHere, MSGBOX_NPC
# 11 "data/maps/BattleFrontier_Lounge4/scripts.pory"
	end
# 12 "data/maps/BattleFrontier_Lounge4/scripts.pory"

# 13 "data/maps/BattleFrontier_Lounge4/scripts.pory"
BattleFrontier_Lounge4_EventScript_Man:: @ 826359F
# 14 "data/maps/BattleFrontier_Lounge4/scripts.pory"
	msgbox BattleFrontier_Lounge4_Text_NeedBreatherAfterBattles, MSGBOX_NPC
# 15 "data/maps/BattleFrontier_Lounge4/scripts.pory"
	end
# 16 "data/maps/BattleFrontier_Lounge4/scripts.pory"

# 17 "data/maps/BattleFrontier_Lounge4/scripts.pory"
BattleFrontier_Lounge4_Text_WonderIfInterviewsAiring: @ 82635A8
# 18 "data/maps/BattleFrontier_Lounge4/scripts.pory"
	.string "I wonder if they'll be airing interviews\n"
# 19 "data/maps/BattleFrontier_Lounge4/scripts.pory"
	.string "with tough Trainers today?$"
# 20 "data/maps/BattleFrontier_Lounge4/scripts.pory"

# 21 "data/maps/BattleFrontier_Lounge4/scripts.pory"
BattleFrontier_Lounge4_Text_IfIOpenedRestaurantHere: @ 82635EC
# 22 "data/maps/BattleFrontier_Lounge4/scripts.pory"
	.string "If I opened a restaurant here,\n"
# 23 "data/maps/BattleFrontier_Lounge4/scripts.pory"
	.string "it'd make money for sure.$"
# 24 "data/maps/BattleFrontier_Lounge4/scripts.pory"

# 25 "data/maps/BattleFrontier_Lounge4/scripts.pory"
BattleFrontier_Lounge4_Text_NeedBreatherAfterBattles: @ 8263625
# 26 "data/maps/BattleFrontier_Lounge4/scripts.pory"
	.string "Whew…\p"
# 27 "data/maps/BattleFrontier_Lounge4/scripts.pory"
	.string "I need to take a breather after\n"
# 28 "data/maps/BattleFrontier_Lounge4/scripts.pory"
	.string "some intense battles…\p"
# 29 "data/maps/BattleFrontier_Lounge4/scripts.pory"
	.string "But even now, I never take a break\n"
# 30 "data/maps/BattleFrontier_Lounge4/scripts.pory"
	.string "from plotting strategy and combos.$"
