# 1 "data/maps/OldaleTown_BattleMart/scripts.pory"

# 2 "data/maps/OldaleTown_BattleMart/scripts.pory"
OldaleTown_BattleMart_MapScripts::
# 3 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.byte 0

	.align 2
# 6 "data/maps/OldaleTown_BattleMart/scripts.pory"
OldaleTown_House1_EventScript_Pokemart:
# 7 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_ADAMANT_MINT
# 8 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_BOLD_MINT
# 9 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_BRAVE_MINT
# 10 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_CALM_MINT
# 11 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_CAREFUL_MINT
# 12 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_GENTLE_MINT
# 13 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_HASTY_MINT
# 14 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_IMPISH_MINT
# 15 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_JOLLY_MINT
# 16 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_LAX_MINT
# 17 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_LONELY_MINT
# 18 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_MILD_MINT
# 19 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_MODEST_MINT
# 20 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_NAIVE_MINT
# 21 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_NAUGHTY_MINT
# 22 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_QUIET_MINT
# 23 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_RASH_MINT
# 24 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_RELAXED_MINT
# 25 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_SASSY_MINT
# 26 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_SERIOUS_MINT
# 27 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_TIMID_MINT
# 28 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_ABILITY_CAPSULE
# 29 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_ABILITY_PATCH
# 30 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_EXIOLITE
# 31 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_EVIOLITE
	.2byte ITEM_NONE

	.align 2
# 34 "data/maps/OldaleTown_BattleMart/scripts.pory"
OldaleTown_House1_EventScript_Pokemart_Stones:
# 35 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_FIRE_STONE
# 36 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_WATER_STONE
# 37 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_THUNDER_STONE
# 38 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_LEAF_STONE
# 39 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_SUN_STONE
# 40 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_MOON_STONE
# 41 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_DAWN_STONE
# 42 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_DUSK_STONE
# 43 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_SHINY_STONE
# 44 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_ICE_STONE
# 45 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_LINK_CABLE
# 46 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_SWEET_APPLE
# 47 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_TART_APPLE
# 48 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_SYRUP_APPLE
# 49 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_RAINBOW_SWEET
# 50 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_DRAGON_SCALE
# 51 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_KINGS_ROCK
# 52 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_METAL_COAT
# 53 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_UP_GRADE
# 54 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_DEEP_SEA_SCALE
# 55 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_DEEP_SEA_TOOTH
# 56 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_DUBIOUS_DISC
# 57 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_ELECTIRIZER
# 58 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_MAGMARIZER
# 59 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_OVAL_STONE
# 60 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_PROTECTOR
# 61 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_RAZOR_CLAW
# 62 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_RAZOR_FANG
# 63 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_REAPER_CLOTH
# 64 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_PRISM_SCALE
# 65 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_SACHET
# 66 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_WHIPPED_DREAM
# 67 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_UNREMARKABLE_TEACUP
# 68 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_MASTERPIECE_TEACUP
# 69 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_PEAT_BLOCK
# 70 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_AUSPICIOUS_ARMOR
# 71 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_MALICIOUS_ARMOR
# 74 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_METAL_ALLOY
# 75 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_BLACK_AUGURITE
# 76 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_CHIPPED_POT
# 77 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_CRACKED_POT
# 78 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_GALARICA_CUFF
# 79 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_GALARICA_TWIG
	.2byte ITEM_NONE

	.align 2
# 83 "data/maps/OldaleTown_BattleMart/scripts.pory"
MartEnergyGuruMons:
# 84 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte SPECIES_ABRA
# 85 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte SPECIES_CLEFFA
# 86 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte SPECIES_MIMEJR
# 87 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte SPECIES_DRATINI
# 88 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte SPECIES_EEVEE
# 89 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte SPECIES_PORYGON
	.2byte ITEM_NONE

OldaleTown_BattleMart_EventScript_Man::
# 93 "data/maps/OldaleTown_BattleMart/scripts.pory"
	lock
# 94 "data/maps/OldaleTown_BattleMart/scripts.pory"
	faceplayer
# 95 "data/maps/OldaleTown_BattleMart/scripts.pory"
	msgbox OldaleTown_BattleMart_EventScript_Man_Text_0
# 96 "data/maps/OldaleTown_BattleMart/scripts.pory"
	release
	end


OldaleTown_House1_EventScript_BattleMart::
# 101 "data/maps/OldaleTown_BattleMart/scripts.pory"
	lock
# 102 "data/maps/OldaleTown_BattleMart/scripts.pory"
	faceplayer
# 103 "data/maps/OldaleTown_BattleMart/scripts.pory"
	setvar VAR_SHOP_TYPE, MART_TYPE_NORMAL
# 104 "data/maps/OldaleTown_BattleMart/scripts.pory"
	setvar VAR_SHOP_MONEY_TYPE, MART_MONEY_TYPE_BATTLE_POINTS
# 105 "data/maps/OldaleTown_BattleMart/scripts.pory"
	message OldaleTown_House1_EventScript_BattleMart_Text_0
# 106 "data/maps/OldaleTown_BattleMart/scripts.pory"
	waitmessage
# 107 "data/maps/OldaleTown_BattleMart/scripts.pory"
	pokemart OldaleTown_House1_EventScript_Pokemart
# 108 "data/maps/OldaleTown_BattleMart/scripts.pory"
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
# 109 "data/maps/OldaleTown_BattleMart/scripts.pory"
	release
	end


OldaleTown_House1_EventScript_BattleMart_Stones::
# 114 "data/maps/OldaleTown_BattleMart/scripts.pory"
	lock
# 115 "data/maps/OldaleTown_BattleMart/scripts.pory"
	faceplayer
# 116 "data/maps/OldaleTown_BattleMart/scripts.pory"
	setvar VAR_SHOP_TYPE, MART_TYPE_NORMAL
# 117 "data/maps/OldaleTown_BattleMart/scripts.pory"
	setvar VAR_SHOP_MONEY_TYPE, MART_MONEY_TYPE_BATTLE_POINTS
# 118 "data/maps/OldaleTown_BattleMart/scripts.pory"
	message OldaleTown_House1_EventScript_BattleMart_Text_0
# 119 "data/maps/OldaleTown_BattleMart/scripts.pory"
	waitmessage
# 120 "data/maps/OldaleTown_BattleMart/scripts.pory"
	pokemart OldaleTown_House1_EventScript_Pokemart_Stones
# 121 "data/maps/OldaleTown_BattleMart/scripts.pory"
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
# 122 "data/maps/OldaleTown_BattleMart/scripts.pory"
	release
	end


MauvilleCity_GameCorner_EventScript_Mons::
# 127 "data/maps/OldaleTown_BattleMart/scripts.pory"
	lock
# 128 "data/maps/OldaleTown_BattleMart/scripts.pory"
	faceplayer
# 129 "data/maps/OldaleTown_BattleMart/scripts.pory"
	setvar VAR_SHOP_TYPE, MART_TYPE_MONS
# 130 "data/maps/OldaleTown_BattleMart/scripts.pory"
	setvar VAR_SHOP_MONEY_TYPE, MART_MONEY_TYPE_BATTLE_POINTS
# 131 "data/maps/OldaleTown_BattleMart/scripts.pory"
	message MauvilleCity_GameCorner_EventScript_Mons_Text_0
# 132 "data/maps/OldaleTown_BattleMart/scripts.pory"
	waitmessage
# 133 "data/maps/OldaleTown_BattleMart/scripts.pory"
	pokemart MartEnergyGuruMons
# 134 "data/maps/OldaleTown_BattleMart/scripts.pory"
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
# 135 "data/maps/OldaleTown_BattleMart/scripts.pory"
	release
	end


	.align 2
# 139 "data/maps/OldaleTown_BattleMart/scripts.pory"
OldaleTown_House1_EventScript_Pokemart_HeldItems:
# 140 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_SOOTHE_BELL
# 141 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_AMULET_COIN
# 142 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_EVERSTONE
# 143 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_LUCKY_EGG
# 144 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_NORMAL_GEM
# 145 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_QUICK_CLAW
# 146 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_CHOICE_BAND
# 147 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_CHOICE_SCARF
# 148 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_CHOICE_SPECS
# 149 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_SCOPE_LENS
# 150 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_LIFE_ORB
# 151 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_TOXIC_ORB
# 152 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_FLAME_ORB
# 153 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_FOCUS_SASH
# 154 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_WHITE_HERB
# 155 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_POWER_HERB
# 156 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_MENTAL_HERB
# 157 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_BLACK_SLUDGE
# 158 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_ASSAULT_VEST
# 159 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_UTILITY_UMBRELLA
# 160 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_WEAKNESS_POLICY
# 161 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_HEAVY_DUTY_BOOTS
# 162 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_ROCKY_HELMET
# 163 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_FOCUS_BAND
# 164 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_LUM_BERRY
# 165 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_POWER_BRACER
# 166 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_POWER_BELT
# 167 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_POWER_LENS
# 168 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_POWER_BAND
# 169 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_POWER_ANKLET
# 170 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_MACHO_BRACE
# 171 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_TERRAIN_EXTENDER
# 172 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_WIDE_LENS
# 173 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_SHELL_BELL
# 174 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_ZOOM_LENS
# 175 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_EXPERT_BELT
# 176 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_METRONOME
# 177 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_SHED_SHELL
# 178 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_RED_CARD
# 179 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_SAFETY_GOGGLES
# 180 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_ADRENALINE_ORB
# 181 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_PROTECTIVE_PADS
	.2byte ITEM_NONE

	.align 2
# 185 "data/maps/OldaleTown_BattleMart/scripts.pory"
OldaleTown_House1_EventScript_Pokemart_TMs:
# 186 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_TM14
# 187 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_TM15
# 188 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_TM25
# 189 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_TM38
# 190 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_TM59
# 191 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_TM30
# 192 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_TM66
# 193 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_TM75
# 194 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_TM82
# 195 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_TM84
# 196 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_TM97
# 197 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_TM109
# 198 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.2byte ITEM_TM115
	.2byte ITEM_NONE

EightIsland_House1_EventScript_BattleMart_TMs::
# 203 "data/maps/OldaleTown_BattleMart/scripts.pory"
	lock
# 204 "data/maps/OldaleTown_BattleMart/scripts.pory"
	faceplayer
# 205 "data/maps/OldaleTown_BattleMart/scripts.pory"
	setvar VAR_SHOP_TYPE, MART_TYPE_NORMAL
# 206 "data/maps/OldaleTown_BattleMart/scripts.pory"
	setvar VAR_SHOP_MONEY_TYPE, MART_MONEY_TYPE_BATTLE_POINTS
# 207 "data/maps/OldaleTown_BattleMart/scripts.pory"
	message OldaleTown_House1_EventScript_BattleMart_Text_0
# 208 "data/maps/OldaleTown_BattleMart/scripts.pory"
	waitmessage
# 209 "data/maps/OldaleTown_BattleMart/scripts.pory"
	pokemart OldaleTown_House1_EventScript_Pokemart_TMs
# 210 "data/maps/OldaleTown_BattleMart/scripts.pory"
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
# 211 "data/maps/OldaleTown_BattleMart/scripts.pory"
	release
	end


EightIsland_House1_EventScript_BattleMart_HeldItems::
# 216 "data/maps/OldaleTown_BattleMart/scripts.pory"
	lock
# 217 "data/maps/OldaleTown_BattleMart/scripts.pory"
	faceplayer
# 218 "data/maps/OldaleTown_BattleMart/scripts.pory"
	setvar VAR_SHOP_TYPE, MART_TYPE_NORMAL
# 219 "data/maps/OldaleTown_BattleMart/scripts.pory"
	setvar VAR_SHOP_MONEY_TYPE, MART_MONEY_TYPE_BATTLE_POINTS
# 220 "data/maps/OldaleTown_BattleMart/scripts.pory"
	message OldaleTown_House1_EventScript_BattleMart_Text_0
# 221 "data/maps/OldaleTown_BattleMart/scripts.pory"
	waitmessage
# 222 "data/maps/OldaleTown_BattleMart/scripts.pory"
	pokemart OldaleTown_House1_EventScript_Pokemart_HeldItems
# 223 "data/maps/OldaleTown_BattleMart/scripts.pory"
	msgbox gText_PleaseComeAgain, MSGBOX_DEFAULT
# 224 "data/maps/OldaleTown_BattleMart/scripts.pory"
	release
	end


OldaleTown_BattleMart_EventScript_Man_Text_0:
# 95 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.string "Thanks to Nature Mints, I was able to\n"
	.string "change my Pokémon's nature from\l"
	.string "Adamant to Timid!$"

OldaleTown_House1_EventScript_BattleMart_Text_0:
# 105 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.string "Welcome to my Battle Mart!, How may I\n"
	.string "serve you?$"

MauvilleCity_GameCorner_EventScript_Mons_Text_0:
# 131 "data/maps/OldaleTown_BattleMart/scripts.pory"
	.string "I'm currently selling some Pokémon for\n"
	.string "BP!, How may I serve you?$"
