# 1 "data/maps/VerdanturfTown_House/scripts.pory"

# 2 "data/maps/VerdanturfTown_House/scripts.pory"
VerdanturfTown_House_MapScripts:: @ 820335E
# 3 "data/maps/VerdanturfTown_House/scripts.pory"
	.byte 0
# 4 "data/maps/VerdanturfTown_House/scripts.pory"

# 5 "data/maps/VerdanturfTown_House/scripts.pory"
VerdanturfTown_House_EventScript_Woman1:: @ 820335F
# 6 "data/maps/VerdanturfTown_House/scripts.pory"
	msgbox VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague, MSGBOX_NPC
# 7 "data/maps/VerdanturfTown_House/scripts.pory"
	end
# 8 "data/maps/VerdanturfTown_House/scripts.pory"

# 9 "data/maps/VerdanturfTown_House/scripts.pory"
VerdanturfTown_House_EventScript_Woman2:: @ 8203368
# 10 "data/maps/VerdanturfTown_House/scripts.pory"
	msgbox VerdanturfTown_House_Text_DefeatEliteFourInARow, MSGBOX_NPC
# 11 "data/maps/VerdanturfTown_House/scripts.pory"
	end
# 12 "data/maps/VerdanturfTown_House/scripts.pory"

# 13 "data/maps/VerdanturfTown_House/scripts.pory"
VerdanturfTown_House_Text_TrainersGatherAtPokemonLeague: @ 8203371
# 14 "data/maps/VerdanturfTown_House/scripts.pory"
	.string "Far away, deep in Ever Grande City,\n"
# 15 "data/maps/VerdanturfTown_House/scripts.pory"
	.string "is the Pokémon League.\p"
# 16 "data/maps/VerdanturfTown_House/scripts.pory"
	.string "The Trainers who gather there are\n"
# 17 "data/maps/VerdanturfTown_House/scripts.pory"
	.string "all frighteningly well skilled.$"
# 18 "data/maps/VerdanturfTown_House/scripts.pory"

# 19 "data/maps/VerdanturfTown_House/scripts.pory"
VerdanturfTown_House_Text_DefeatEliteFourInARow: @ 82033EE
# 20 "data/maps/VerdanturfTown_House/scripts.pory"
	.string "In the Pokémon League, I think the\n"
# 21 "data/maps/VerdanturfTown_House/scripts.pory"
	.string "rules say that you have to battle the\l"
# 22 "data/maps/VerdanturfTown_House/scripts.pory"
	.string "Elite Four all in a row.\p"
# 23 "data/maps/VerdanturfTown_House/scripts.pory"
	.string "If you lose to any of them, you have\n"
# 24 "data/maps/VerdanturfTown_House/scripts.pory"
	.string "to begin your challenge again from the\l"
# 25 "data/maps/VerdanturfTown_House/scripts.pory"
	.string "first one.$"
