# 1 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 2 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_MapScripts:: @ 825E4A9
# 3 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.byte 0
# 4 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 5 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_EventScript_TowerSinglesRecords:: @ 825E4AA
# 6 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	lockall
# 7 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	setvar VAR_0x8005, RANKING_HALL_BATTLE_TOWER_SINGLES
# 8 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	goto BattleFrontier_RankingHall_EventScript_ShowRecords
# 9 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	end
# 10 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 11 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_EventScript_TowerDoublesRecords:: @ 825E4B6
# 12 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	lockall
# 13 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	setvar VAR_0x8005, RANKING_HALL_BATTLE_TOWER_DOUBLES
# 14 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	goto BattleFrontier_RankingHall_EventScript_ShowRecords
# 15 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	end
# 16 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 17 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_EventScript_TowerMultisRecords:: @ 825E4C2
# 18 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	lockall
# 19 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	setvar VAR_0x8005, RANKING_HALL_BATTLE_TOWER_MULTIS
# 20 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	goto BattleFrontier_RankingHall_EventScript_ShowRecords
# 21 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	end
# 22 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 23 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_EventScript_TowerLinkRecords:: @ 825E4CE
# 24 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	lockall
# 25 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	setvar VAR_0x8005, RANKING_HALL_BATTLE_TOWER_LINK
# 26 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	goto BattleFrontier_RankingHall_EventScript_ShowRecords
# 27 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	end
# 28 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 29 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_EventScript_ArenaRecords:: @ 825E4DA
# 30 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	lockall
# 31 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	setvar VAR_0x8005, RANKING_HALL_BATTLE_ARENA
# 32 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	goto BattleFrontier_RankingHall_EventScript_ShowRecords
# 33 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	end
# 34 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 35 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_EventScript_PalaceRecords:: @ 825E4E6
# 36 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	lockall
# 37 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	setvar VAR_0x8005, RANKING_HALL_BATTLE_PALACE
# 38 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	goto BattleFrontier_RankingHall_EventScript_ShowRecords
# 39 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	end
# 40 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 41 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_EventScript_FactoryRecords:: @ 825E4F2
# 42 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	lockall
# 43 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	setvar VAR_0x8005, RANKING_HALL_BATTLE_FACTORY
# 44 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	goto BattleFrontier_RankingHall_EventScript_ShowRecords
# 45 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	end
# 46 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 47 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_EventScript_DomeRecords:: @ 825E4FE
# 48 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	lockall
# 49 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	setvar VAR_0x8005, RANKING_HALL_BATTLE_DOME
# 50 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	goto BattleFrontier_RankingHall_EventScript_ShowRecords
# 51 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	end
# 52 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 53 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_EventScript_PikeRecords:: @ 825E50A
# 54 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	lockall
# 55 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	setvar VAR_0x8005, RANKING_HALL_BATTLE_PIKE
# 56 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	goto BattleFrontier_RankingHall_EventScript_ShowRecords
# 57 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	end
# 58 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 59 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_EventScript_PyramidRecords:: @ 825E516
# 60 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	lockall
# 61 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	setvar VAR_0x8005, RANKING_HALL_BATTLE_PYRAMID
# 62 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	goto BattleFrontier_RankingHall_EventScript_ShowRecords
# 63 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	end
# 64 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 65 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_EventScript_ShowRecords:: @ 825E522
# 66 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	special ShowRankingHallRecordsWindow
# 67 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	waitbuttonpress
# 68 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	special ScrollRankingHallRecordsWindow
# 69 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	waitbuttonpress
# 70 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	special RemoveRecordsWindow
# 71 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	releaseall
# 72 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	end
# 73 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 74 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_EventScript_Attendant:: @ 825E52F
# 75 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	msgbox BattleFrontier_RankingHall_Text_ExplainRankingHall, MSGBOX_NPC
# 76 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	end
# 77 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 78 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_EventScript_DomePikeFactoryRecordsSign:: @ 825E538
# 79 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	msgbox BattleFrontier_RankingHall_Text_DomePikeFactoryRecords, MSGBOX_SIGN
# 80 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	end
# 81 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 82 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_EventScript_PalaceArenaPyramidRecordsSIgn:: @ 825E541
# 83 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	msgbox BattleFrontier_RankingHall_Text_PalaceArenaPyramidRecords, MSGBOX_SIGN
# 84 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	end
# 85 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 86 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_EventScript_NinjaBoy:: @ 825E54A
# 87 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	lock
# 88 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	faceplayer
# 89 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	msgbox BattleFrontier_RankingHall_Text_IsYourNameOnThisList, MSGBOX_YESNO
# 90 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	compare VAR_RESULT, YES
# 91 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	goto_if_eq BattleFrontier_RankingHall_EventScript_NinjaBoyNameOnList
# 92 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	msgbox BattleFrontier_RankingHall_Text_WorkHarderIfYouSawFriendsName, MSGBOX_DEFAULT
# 93 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	release
# 94 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	end
# 95 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 96 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_EventScript_NinjaBoyNameOnList:: @ 825E569
# 97 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	msgbox BattleFrontier_RankingHall_Text_WowThatsSuper, MSGBOX_DEFAULT
# 98 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	release
# 99 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	end
# 100 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 101 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_EventScript_Boy:: @ 825E573
# 102 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	msgbox BattleFrontier_RankingHall_Text_MyNamesNotUpThere, MSGBOX_NPC
# 103 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	end
# 104 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 105 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_Text_ExplainRankingHall: @ 825E57C
# 106 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "This is the Ranking Hall.\p"
# 107 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "This is where we recognize the immortal\n"
# 108 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "Trainers who left great records in\l"
# 109 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "Battle Frontier events.$"
# 110 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 111 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_Text_DomePikeFactoryRecords: @ 825E5F9
# 112 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "Battle Dome, Battle Pike,\n"
# 113 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "and Battle Factory Records$"
# 114 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 115 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_Text_PalaceArenaPyramidRecords: @ 825E62E
# 116 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "Battle Palace, Battle Arena,\n"
# 117 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "and Battle Pyramid Records$"
# 118 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 119 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_Text_IsYourNameOnThisList: @ 825E666
# 120 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "Hi, is your name on this list?$"
# 121 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 122 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_Text_WowThatsSuper: @ 825E685
# 123 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "Wow, that's super!\n"
# 124 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "I'll have to try harder, too!$"
# 125 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 126 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_Text_WorkHarderIfYouSawFriendsName: @ 825E6B6
# 127 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "Oh, is that right?\p"
# 128 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "If you saw your friend's name up here,\n"
# 129 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "I bet it would make you work harder!$"
# 130 "data/maps/BattleFrontier_RankingHall/scripts.pory"

# 131 "data/maps/BattleFrontier_RankingHall/scripts.pory"
BattleFrontier_RankingHall_Text_MyNamesNotUpThere: @ 825E715
# 132 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "Hmm…\n"
# 133 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "My name's not up there…\p"
# 134 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "Well, it's only natural since I haven't\n"
# 135 "data/maps/BattleFrontier_RankingHall/scripts.pory"
	.string "taken any challenges yet.$"
