# 1 "data/maps/OldaleTown_House1/scripts.pory"

# 2 "data/maps/OldaleTown_House1/scripts.pory"
OldaleTown_House1_MapScripts:: @ 81FBE85
# 3 "data/maps/OldaleTown_House1/scripts.pory"
	.byte 0
# 4 "data/maps/OldaleTown_House1/scripts.pory"

# 5 "data/maps/OldaleTown_House1/scripts.pory"
OldaleTown_House1_EventScript_Woman:: @ 81FBE86
# 6 "data/maps/OldaleTown_House1/scripts.pory"
	msgbox OldaleTown_House1_Text_LeftPokemonGoesOutFirst, MSGBOX_NPC
# 7 "data/maps/OldaleTown_House1/scripts.pory"
	end
# 8 "data/maps/OldaleTown_House1/scripts.pory"

# 9 "data/maps/OldaleTown_House1/scripts.pory"
OldaleTown_House1_Text_LeftPokemonGoesOutFirst: @ 81FBE8F
# 10 "data/maps/OldaleTown_House1/scripts.pory"
	.string "When a Pokémon battle starts, the one\n"
# 11 "data/maps/OldaleTown_House1/scripts.pory"
	.string "at the left of the list goes out first.\p"
# 12 "data/maps/OldaleTown_House1/scripts.pory"
	.string "So, when you get more Pokémon in your\n"
# 13 "data/maps/OldaleTown_House1/scripts.pory"
	.string "party, try switching around the order\l"
# 14 "data/maps/OldaleTown_House1/scripts.pory"
	.string "of your Pokémon.\p"
# 15 "data/maps/OldaleTown_House1/scripts.pory"
	.string "It could give you an advantage.$"
