FourIsland_LoreleisHouse_EventScript_Lorelei::
# 4 "data/scripts/sevii_scripts.pory"
	lock
# 5 "data/scripts/sevii_scripts.pory"
	faceplayer
# 6 "data/scripts/sevii_scripts.pory"
	msgbox FourIsland_LoreleisHouse_EventScript_Lorelei_Text_0, MSGBOX_DEFAULT
# 7 "data/scripts/sevii_scripts.pory"
	releaseall
	end


FourIsland_LoreleisHouse_EventScript_Doll::
# 12 "data/scripts/sevii_scripts.pory"
	lock
# 13 "data/scripts/sevii_scripts.pory"
	msgbox FourIsland_LoreleisHouse_EventScript_Doll_Text_0, MSGBOX_DEFAULT
# 14 "data/scripts/sevii_scripts.pory"
	releaseall
	end


FourIsland_House1_EventScript_FatMan::
# 19 "data/scripts/sevii_scripts.pory"
	lock
# 20 "data/scripts/sevii_scripts.pory"
	faceplayer
# 21 "data/scripts/sevii_scripts.pory"
	msgbox FourIsland_House1_EventScript_FatMan_Text_0, MSGBOX_DEFAULT
# 22 "data/scripts/sevii_scripts.pory"
	releaseall
	end


FourIsland_House1_EventScript_BodySlamTutor::
# 27 "data/scripts/sevii_scripts.pory"
	lock
# 28 "data/scripts/sevii_scripts.pory"
	faceplayer
# 29 "data/scripts/sevii_scripts.pory"
	msgbox FourIsland_House1_EventScript_FatMan_Text_0, MSGBOX_DEFAULT
# 30 "data/scripts/sevii_scripts.pory"
	releaseall
	end


FourIsland_House2_EventScript_StickerMan::
# 35 "data/scripts/sevii_scripts.pory"
	lock
# 36 "data/scripts/sevii_scripts.pory"
	faceplayer
# 37 "data/scripts/sevii_scripts.pory"
	msgbox FourIsland_House2_EventScript_StickerMan_Text_0, MSGBOX_DEFAULT
# 38 "data/scripts/sevii_scripts.pory"
	releaseall
	end


FiveIsland_PokemonCenter_1F_EventScript_Chef::
# 44 "data/scripts/sevii_scripts.pory"
	lock
# 45 "data/scripts/sevii_scripts.pory"
	faceplayer
# 46 "data/scripts/sevii_scripts.pory"
	msgbox FiveIsland_PokemonCenter_1F_EventScript_Chef_Text_0, MSGBOX_DEFAULT
# 47 "data/scripts/sevii_scripts.pory"
	releaseall
	end


FiveIsland_PokemonCenter_1F_EventScript_CooltrainerF::
# 52 "data/scripts/sevii_scripts.pory"
	lock
# 53 "data/scripts/sevii_scripts.pory"
	faceplayer
# 54 "data/scripts/sevii_scripts.pory"
	msgbox FiveIsland_PokemonCenter_1F_EventScript_CooltrainerF_Text_0, MSGBOX_DEFAULT
# 55 "data/scripts/sevii_scripts.pory"
	releaseall
	end


FiveIsland_House1_EventScript_Woman::
# 60 "data/scripts/sevii_scripts.pory"
	lock
# 61 "data/scripts/sevii_scripts.pory"
	faceplayer
# 62 "data/scripts/sevii_scripts.pory"
	msgbox FiveIsland_House1_EventScript_Woman_Text_0, MSGBOX_DEFAULT
# 63 "data/scripts/sevii_scripts.pory"
	releaseall
	end


FiveIsland_House2_EventScript_OldMan::
# 68 "data/scripts/sevii_scripts.pory"
	lock
# 69 "data/scripts/sevii_scripts.pory"
	faceplayer
# 70 "data/scripts/sevii_scripts.pory"
	msgbox FiveIsland_House2_EventScript_OldMan_Text_0, MSGBOX_DEFAULT
# 71 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SixIsland_EventScript_Boy::
# 77 "data/scripts/sevii_scripts.pory"
	lock
# 78 "data/scripts/sevii_scripts.pory"
	faceplayer
# 79 "data/scripts/sevii_scripts.pory"
	msgbox SixIsland_EventScript_Boy_Text_0, MSGBOX_DEFAULT
# 80 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SixIsland_EventScript_Hiker::
# 85 "data/scripts/sevii_scripts.pory"
	lock
# 86 "data/scripts/sevii_scripts.pory"
	faceplayer
# 87 "data/scripts/sevii_scripts.pory"
	msgbox SixIsland_EventScript_Hiker_Text_0, MSGBOX_DEFAULT
# 88 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SixIsland_PokemonCenter_1F_EventScript_OldMan::
# 94 "data/scripts/sevii_scripts.pory"
	lock
# 95 "data/scripts/sevii_scripts.pory"
	faceplayer
# 96 "data/scripts/sevii_scripts.pory"
	msgbox SixIsland_PokemonCenter_1F_EventScript_OldMan_Text_0, MSGBOX_DEFAULT
# 97 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SixIsland_PokemonCenter_1F_EventScript_Hiker::
# 102 "data/scripts/sevii_scripts.pory"
	lock
# 103 "data/scripts/sevii_scripts.pory"
	faceplayer
# 104 "data/scripts/sevii_scripts.pory"
	msgbox SixIsland_PokemonCenter_1F_EventScript_Hiker_Text_0, MSGBOX_DEFAULT
# 105 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SixIsland_Mart_EventScript_Picnicker::
# 111 "data/scripts/sevii_scripts.pory"
	lock
# 112 "data/scripts/sevii_scripts.pory"
	faceplayer
# 113 "data/scripts/sevii_scripts.pory"
	msgbox SixIsland_Mart_EventScript_Picnicker_Text_0, MSGBOX_DEFAULT
# 114 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SixIsland_Mart_EventScript_OldWoman::
# 119 "data/scripts/sevii_scripts.pory"
	lock
# 120 "data/scripts/sevii_scripts.pory"
	faceplayer
# 121 "data/scripts/sevii_scripts.pory"
	msgbox SixIsland_Mart_EventScript_OldWoman_Text_0, MSGBOX_DEFAULT
# 122 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SixIsland_House_EventScript_OldMan::
# 128 "data/scripts/sevii_scripts.pory"
	lock
# 129 "data/scripts/sevii_scripts.pory"
	faceplayer
# 130 "data/scripts/sevii_scripts.pory"
	msgbox SixIsland_House_EventScript_OldMan_Text_0, MSGBOX_DEFAULT
# 131 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SevenIsland_EventScript_Scientist::
# 137 "data/scripts/sevii_scripts.pory"
	lock
# 138 "data/scripts/sevii_scripts.pory"
	faceplayer
# 139 "data/scripts/sevii_scripts.pory"
	msgbox SevenIsland_EventScript_Scientist_Text_0, MSGBOX_DEFAULT
# 140 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SevenIsland_EventScript_SwordsDanceTutor::
# 145 "data/scripts/sevii_scripts.pory"
	lock
# 146 "data/scripts/sevii_scripts.pory"
	faceplayer
# 147 "data/scripts/sevii_scripts.pory"
	msgbox SevenIsland_EventScript_SwordsDanceTutor_Text_0, MSGBOX_DEFAULT
# 148 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SevenIsland_EventScript_OldWoman::
# 153 "data/scripts/sevii_scripts.pory"
	lock
# 154 "data/scripts/sevii_scripts.pory"
	faceplayer
# 155 "data/scripts/sevii_scripts.pory"
	msgbox SevenIsland_EventScript_OldWoman_Text_0, MSGBOX_DEFAULT
# 156 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SevenIsland_PokemonCenter_1F_EventScript_Beauty::
# 162 "data/scripts/sevii_scripts.pory"
	lock
# 163 "data/scripts/sevii_scripts.pory"
	faceplayer
# 164 "data/scripts/sevii_scripts.pory"
	msgbox SevenIsland_PokemonCenter_1F_EventScript_Beauty_Text_0, MSGBOX_DEFAULT
# 165 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SevenIsland_PokemonCenter_1F_EventScript_OldMan::
# 170 "data/scripts/sevii_scripts.pory"
	lock
# 171 "data/scripts/sevii_scripts.pory"
	faceplayer
# 172 "data/scripts/sevii_scripts.pory"
	msgbox SevenIsland_PokemonCenter_1F_EventScript_OldMan_Text_0, MSGBOX_DEFAULT
# 173 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SevenIsland_PokemonCenter_1F_EventScript_Sailor::
# 178 "data/scripts/sevii_scripts.pory"
	lock
# 179 "data/scripts/sevii_scripts.pory"
	faceplayer
# 180 "data/scripts/sevii_scripts.pory"
	msgbox SevenIsland_PokemonCenter_1F_EventScript_Sailor_Text_0, MSGBOX_DEFAULT
# 181 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SevenIsland_Mart_EventScript_Hiker::
# 187 "data/scripts/sevii_scripts.pory"
	lock
# 188 "data/scripts/sevii_scripts.pory"
	faceplayer
# 189 "data/scripts/sevii_scripts.pory"
	msgbox SevenIsland_Mart_EventScript_Hiker_Text_0, MSGBOX_DEFAULT
# 190 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SevenIsland_Mart_EventScript_Fisher::
# 195 "data/scripts/sevii_scripts.pory"
	lock
# 196 "data/scripts/sevii_scripts.pory"
	faceplayer
# 197 "data/scripts/sevii_scripts.pory"
	msgbox SevenIsland_Mart_EventScript_Fisher_Text_0, MSGBOX_DEFAULT
# 198 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SevenIsland_Mart_EventScript_Lass::
# 203 "data/scripts/sevii_scripts.pory"
	lock
# 204 "data/scripts/sevii_scripts.pory"
	faceplayer
# 205 "data/scripts/sevii_scripts.pory"
	msgbox SevenIsland_Mart_EventScript_Lass_Text_0, MSGBOX_DEFAULT
# 206 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SevenIsland_House_Room1_EventScript_OldWoman::
# 212 "data/scripts/sevii_scripts.pory"
	lock
# 213 "data/scripts/sevii_scripts.pory"
	faceplayer
# 214 "data/scripts/sevii_scripts.pory"
	msgbox SevenIsland_House_Room1_EventScript_OldWoman_Text_0, MSGBOX_DEFAULT
# 215 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SixIsland_WaterPath_House1_EventScript_Beauty::
# 220 "data/scripts/sevii_scripts.pory"
	lock
# 221 "data/scripts/sevii_scripts.pory"
	faceplayer
# 222 "data/scripts/sevii_scripts.pory"
	msgbox SixIsland_WaterPath_House1_EventScript_Beauty_Text_0, MSGBOX_DEFAULT
# 223 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SixIsland_WaterPath_House2_EventScript_Man::
# 228 "data/scripts/sevii_scripts.pory"
	lock
# 229 "data/scripts/sevii_scripts.pory"
	faceplayer
# 230 "data/scripts/sevii_scripts.pory"
	msgbox SixIsland_WaterPath_House2_EventScript_Man_Text_0, MSGBOX_DEFAULT
# 231 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SevenIsland_SevaultCanyon_House_EventScript_BaldingMan::
# 236 "data/scripts/sevii_scripts.pory"
	lock
# 237 "data/scripts/sevii_scripts.pory"
	faceplayer
# 238 "data/scripts/sevii_scripts.pory"
	msgbox SevenIsland_SevaultCanyon_House_EventScript_BaldingMan_Text_0, MSGBOX_DEFAULT
# 239 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SevenIsland_SevaultCanyon_House_EventScript_Chansey::
# 244 "data/scripts/sevii_scripts.pory"
	lock
# 245 "data/scripts/sevii_scripts.pory"
	faceplayer
# 246 "data/scripts/sevii_scripts.pory"
	msgbox SevenIsland_SevaultCanyon_House_EventScript_Chansey_Text_0, MSGBOX_DEFAULT
# 247 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SevenIsland_SevaultCanyon_Entrance_EventScript_RouteSign::
# 253 "data/scripts/sevii_scripts.pory"
	lock
# 254 "data/scripts/sevii_scripts.pory"
	msgbox SevenIsland_SevaultCanyon_Entrance_EventScript_RouteSign_Text_0, MSGBOX_DEFAULT
# 255 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SevenIsland_SevaultCanyon_EventScript_RouteSign::
# 260 "data/scripts/sevii_scripts.pory"
	lock
# 261 "data/scripts/sevii_scripts.pory"
	msgbox SevenIsland_SevaultCanyon_EventScript_RouteSign_Text_0, MSGBOX_DEFAULT
# 262 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SixIsland_GreenPath_EventScript_LeftRouteSign::
# 267 "data/scripts/sevii_scripts.pory"
	lock
# 268 "data/scripts/sevii_scripts.pory"
	msgbox SixIsland_GreenPath_EventScript_LeftRouteSign_Text_0, MSGBOX_DEFAULT
# 269 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SixIsland_GreenPath_EventScript_RightRouteSign::
# 274 "data/scripts/sevii_scripts.pory"
	lock
# 275 "data/scripts/sevii_scripts.pory"
	msgbox SixIsland_GreenPath_EventScript_RightRouteSign_Text_0, MSGBOX_DEFAULT
# 276 "data/scripts/sevii_scripts.pory"
	releaseall
	end


SixIsland_EventScript_IslandSign::
# 281 "data/scripts/sevii_scripts.pory"
	msgbox SixIsland_EventScript_IslandSign_Text_0, MSGBOX_SIGN
	end


SevenIsland_EventScript_IslandSign::
# 286 "data/scripts/sevii_scripts.pory"
	msgbox SevenIsland_EventScript_IslandSign_Text_0, MSGBOX_SIGN
	end


SixIsland_WaterPathEventScript_RouteSign::
# 291 "data/scripts/sevii_scripts.pory"
	msgbox SixIsland_WaterPathEventScript_RouteSign_Text_0, MSGBOX_SIGN
	end


FourIsland_LoreleisHouse_EventScript_Lorelei_Text_0:
# 6 "data/scripts/sevii_scripts.pory"
	.string "My niece Lorelei is a famous trainer in\n"
	.string "Kanto, she really likes Ice-type\l"
	.string "Pokémon.$"

FourIsland_LoreleisHouse_EventScript_Doll_Text_0:
# 13 "data/scripts/sevii_scripts.pory"
	.string "It's a Poké-Doll.$"

FourIsland_House1_EventScript_FatMan_Text_0:
# 21 "data/scripts/sevii_scripts.pory"
	.string "There! Boing! You're awfully heavy!$"

FourIsland_House2_EventScript_StickerMan_Text_0:
# 37 "data/scripts/sevii_scripts.pory"
	.string "Giggle… I collected a ton of Stickers, I\n"
	.string "wish I could show them off….$"

FiveIsland_PokemonCenter_1F_EventScript_Chef_Text_0:
# 46 "data/scripts/sevii_scripts.pory"
	.string "I'm on my way to prepare a meal for a\n"
	.string "certain high-society person.$"

FiveIsland_PokemonCenter_1F_EventScript_CooltrainerF_Text_0:
# 54 "data/scripts/sevii_scripts.pory"
	.string "You're on a quest to catch every single\n"
	.string "kind of Pokémon? …How incredible.\l"
	.string "Please tell me if you catch a strong\l"
	.string "one!.$"

FiveIsland_House1_EventScript_Woman_Text_0:
# 62 "data/scripts/sevii_scripts.pory"
	.string "Don't worry about buying anything for\n"
	.string "dinner tonight! …That's what my\l"
	.string "husband said when he went off fishing\l"
	.string "today. I'm not sure if I can count on him\l"
	.string "to live up to that promise..$"

FiveIsland_House2_EventScript_OldMan_Text_0:
# 70 "data/scripts/sevii_scripts.pory"
	.string "That Meadow has belonged to our family\n"
	.string "for generations. I should have had a\l"
	.string "giant mansion built on it. It would be\l"
	.string "preferable to having those thugs run\l"
	.string "wild on it!.$"

SixIsland_EventScript_Boy_Text_0:
# 79 "data/scripts/sevii_scripts.pory"
	.string "When you're this far away from the city,\n"
	.string "the sky at night is fantastic..$"

SixIsland_EventScript_Hiker_Text_0:
# 87 "data/scripts/sevii_scripts.pory"
	.string "Keep going this way and you'll get to\n"
	.string "the Water Path. Stay on that and you'll\l"
	.string "get to the Ruin Valley.$"

SixIsland_PokemonCenter_1F_EventScript_OldMan_Text_0:
# 96 "data/scripts/sevii_scripts.pory"
	.string "You know of Pokémon that evolve only\n"
	.string "upon trading, yes? But did you know\l"
	.string "that there are still others? Some\l"
	.string "Pokémon evolve only when traded while\l"
	.string "holding specific items.$"

SixIsland_PokemonCenter_1F_EventScript_Hiker_Text_0:
# 104 "data/scripts/sevii_scripts.pory"
	.string "For ten years, I've searched for Ruins.\n"
	.string "No, make that twenty years. I get this\l"
	.string "feeling that there's something hidden\l"
	.string "on this island..$"

SixIsland_Mart_EventScript_Picnicker_Text_0:
# 113 "data/scripts/sevii_scripts.pory"
	.string "I should buy some Mail and write him a\n"
	.string "letter…$"

SixIsland_Mart_EventScript_OldWoman_Text_0:
# 121 "data/scripts/sevii_scripts.pory"
	.string "Play with Pokémon lots and live a long\n"
	.string "life! Take Agatha, for example. She set\l"
	.string "a record for being the oldest-ever\l"
	.string "Elite Four member. She spurs me to do\l"
	.string "bigger things..$"

SixIsland_House_EventScript_OldMan_Text_0:
# 130 "data/scripts/sevii_scripts.pory"
	.string "There's nothing that young people'd\n"
	.string "find exciting here on this island. But,\l"
	.string "this is a good place in terms of nature\l"
	.string "and history. Relax and enjoy your stay..$"

SevenIsland_EventScript_Scientist_Text_0:
# 139 "data/scripts/sevii_scripts.pory"
	.string "This island has been left virtually\n"
	.string "untouched in its natural state. It\l"
	.string "could be a little difficult to hike\l"
	.string "around because of that..$"

SevenIsland_EventScript_SwordsDanceTutor_Text_0:
# 147 "data/scripts/sevii_scripts.pory"
	.string "I saw some Tentacools that were\n"
	.string "walking on land, that's a really strange\l"
	.string "thing to happen since they are\l"
	.string "Water-type Pokémon...$"

SevenIsland_EventScript_OldWoman_Text_0:
# 155 "data/scripts/sevii_scripts.pory"
	.string "These islands are called the Sevii\n"
	.string "Islands because there are seven. …Or at\l"
	.string "least that's what the young people\l"
	.string "believe. The truth is, these islands are\l"
	.string "so named because they are said to have\l"
	.string "been made in seven days.$"

SevenIsland_PokemonCenter_1F_EventScript_Beauty_Text_0:
# 164 "data/scripts/sevii_scripts.pory"
	.string "If you're confident, you should check\n"
	.string "out Trainer Tower.$"

SevenIsland_PokemonCenter_1F_EventScript_OldMan_Text_0:
# 172 "data/scripts/sevii_scripts.pory"
	.string "On this island, different events occur\n"
	.string "depending on connections. What are\l"
	.string "those connections? They are for you to\l"
	.string "discover on your own..$"

SevenIsland_PokemonCenter_1F_EventScript_Sailor_Text_0:
# 180 "data/scripts/sevii_scripts.pory"
	.string "Did you ride a Seagallop ferry to get\n"
	.string "here? There are at least ten of those\l"
	.string "high-speed ships. I don't know where\l"
	.string "they all go, though.$"

SevenIsland_Mart_EventScript_Hiker_Text_0:
# 189 "data/scripts/sevii_scripts.pory"
	.string "Okay, preparations are complete for me\n"
	.string "to explore the Ruins.$"

SevenIsland_Mart_EventScript_Fisher_Text_0:
# 197 "data/scripts/sevii_scripts.pory"
	.string "I need to fish on Seven Island. That\n"
	.string "will complete my fishing tour of the\l"
	.string "Sevii Islands. I'd better stock up on\l"
	.string "some Poké Balls first, though.$"

SevenIsland_Mart_EventScript_Lass_Text_0:
# 205 "data/scripts/sevii_scripts.pory"
	.string "Pokémon have personalities of their\n"
	.string "own, just like people. My Pikachu has a\l"
	.string "Hasty nature, so it grew to be a speedy\l"
	.string "Pokémon.$"

SevenIsland_House_Room1_EventScript_OldWoman_Text_0:
# 214 "data/scripts/sevii_scripts.pory"
	.string "I may not look like much now, but when I\n"
	.string "was younger… I flew everywhere,\l"
	.string "challenging Trainers wherever I found\l"
	.string "them. Now, my only source of enjoyment\l"
	.string "is reminiscing about the past while\l"
	.string "watching battles..$"

SixIsland_WaterPath_House1_EventScript_Beauty_Text_0:
# 222 "data/scripts/sevii_scripts.pory"
	.string "Hera, hera, Heracross!\n"
	.string "Big and shiny, it's the bug boss!\l"
	.string "Love it, need it, Heracross!$"

SixIsland_WaterPath_House2_EventScript_Man_Text_0:
# 230 "data/scripts/sevii_scripts.pory"
	.string "My height is 67.0 inches on the button.\p"
	.string "I know it is this precisely because my\n"
	.string "neighbor measured me.$"

SevenIsland_SevaultCanyon_House_EventScript_BaldingMan_Text_0:
# 238 "data/scripts/sevii_scripts.pory"
	.string "Dance, dance!\n"
	.string "Chansey Dance!\p"
	.string "You join in, too!\n"
	.string "Dance, dance!$"

SevenIsland_SevaultCanyon_House_EventScript_Chansey_Text_0:
# 246 "data/scripts/sevii_scripts.pory"
	.string "Chansey: Chansi! Chansi!$"

SevenIsland_SevaultCanyon_Entrance_EventScript_RouteSign_Text_0:
# 254 "data/scripts/sevii_scripts.pory"
	.string "Sevault Canyon Entrance trainers are\n"
	.string "asked to refrain from damaging plants\l"
	.string "in the Canyon.$"

SevenIsland_SevaultCanyon_EventScript_RouteSign_Text_0:
# 261 "data/scripts/sevii_scripts.pory"
	.string "Sevault Canyon Tanoby Ruins ahead$"

SixIsland_GreenPath_EventScript_LeftRouteSign_Text_0:
# 268 "data/scripts/sevii_scripts.pory"
	.string "Green Path Pattern Bush Ahead$"

SixIsland_GreenPath_EventScript_RightRouteSign_Text_0:
# 275 "data/scripts/sevii_scripts.pory"
	.string "Green Path, Think Green, Keep Nature\n"
	.string "Clean!$"

SixIsland_EventScript_IslandSign_Text_0:
# 281 "data/scripts/sevii_scripts.pory"
	.string "Six Island\n"
	.string "Fortune Island of Aged Wisdom$"

SevenIsland_EventScript_IslandSign_Text_0:
# 286 "data/scripts/sevii_scripts.pory"
	.string "Seven Island\n"
	.string "Quest Island of Infinity$"

SixIsland_WaterPathEventScript_RouteSign_Text_0:
# 291 "data/scripts/sevii_scripts.pory"
	.string "Water Path\n"
	.string "Leads Ruin Valley$"
