# 1 "data/maps/OneIsland_TreasureBeach/scripts.pory"

# 2 "data/maps/OneIsland_TreasureBeach/scripts.pory"
OneIsland_TreasureBeach_MapScripts::
# 3 "data/maps/OneIsland_TreasureBeach/scripts.pory"
	.byte 0
# 4 "data/maps/OneIsland_TreasureBeach/scripts.pory"
	
# 5 "data/maps/OneIsland_TreasureBeach/scripts.pory"
OneIsland_TreasureBeach_EventScript_Boy:: @ 816876C
# 6 "data/maps/OneIsland_TreasureBeach/scripts.pory"
	msgbox OneIsland_TreasureBeach_Text_GoodThingsWashUpOnBeach, MSGBOX_NPC
# 7 "data/maps/OneIsland_TreasureBeach/scripts.pory"
	end
# 8 "data/maps/OneIsland_TreasureBeach/scripts.pory"

# 9 "data/maps/OneIsland_TreasureBeach/scripts.pory"
OneIsland_TreasureBeach_Text_AmaraIntro:: @ 8189D5A
# 10 "data/maps/OneIsland_TreasureBeach/scripts.pory"
    .string "Lying back, rocked by the waves…\n"
# 11 "data/maps/OneIsland_TreasureBeach/scripts.pory"
    .string "It's exquisite.$"
# 12 "data/maps/OneIsland_TreasureBeach/scripts.pory"

# 13 "data/maps/OneIsland_TreasureBeach/scripts.pory"
OneIsland_TreasureBeach_Text_AmaraDefeat:: @ 8189D8B
# 14 "data/maps/OneIsland_TreasureBeach/scripts.pory"
    .string "I lost…\n"
# 15 "data/maps/OneIsland_TreasureBeach/scripts.pory"
    .string "It feels awful.$"
# 16 "data/maps/OneIsland_TreasureBeach/scripts.pory"

# 17 "data/maps/OneIsland_TreasureBeach/scripts.pory"
OneIsland_TreasureBeach_Text_AmaraPostBattle:: @ 8189DA3
# 18 "data/maps/OneIsland_TreasureBeach/scripts.pory"
    .string "The sea is pleasantly warm in these\n"
# 19 "data/maps/OneIsland_TreasureBeach/scripts.pory"
    .string "parts.$"
# 20 "data/maps/OneIsland_TreasureBeach/scripts.pory"

# 21 "data/maps/OneIsland_TreasureBeach/scripts.pory"
OneIsland_TreasureBeach_Text_GoodThingsWashUpOnBeach:: @ 8189DCE
# 22 "data/maps/OneIsland_TreasureBeach/scripts.pory"
    .string "Good things get washed up by the\n"
# 23 "data/maps/OneIsland_TreasureBeach/scripts.pory"
    .string "ocean current onto this beach.\p"
# 24 "data/maps/OneIsland_TreasureBeach/scripts.pory"
    .string "That's why I often come here for\n"
# 25 "data/maps/OneIsland_TreasureBeach/scripts.pory"
    .string "some beachcombing.$"
