# 1 "data/maps/SlateportCity_House/scripts.pory"

# 2 "data/maps/SlateportCity_House/scripts.pory"
SlateportCity_House_MapScripts:: @ 820D9AE
# 3 "data/maps/SlateportCity_House/scripts.pory"
	.byte 0
# 4 "data/maps/SlateportCity_House/scripts.pory"

# 5 "data/maps/SlateportCity_House/scripts.pory"
SlateportCity_House_EventScript_PokefanM:: @ 820D9AF
# 6 "data/maps/SlateportCity_House/scripts.pory"
	msgbox SlateportCity_House_Text_NatureToDoWithStatGains, MSGBOX_NPC
# 7 "data/maps/SlateportCity_House/scripts.pory"
	end
# 8 "data/maps/SlateportCity_House/scripts.pory"

# 9 "data/maps/SlateportCity_House/scripts.pory"
SlateportCity_House_EventScript_Girl:: @ 820D9B8
# 10 "data/maps/SlateportCity_House/scripts.pory"
	msgbox SlateportCity_House_Text_MustBeGoingToBattleTent, MSGBOX_NPC
# 11 "data/maps/SlateportCity_House/scripts.pory"
	end
# 12 "data/maps/SlateportCity_House/scripts.pory"

# 13 "data/maps/SlateportCity_House/scripts.pory"
SlateportCity_House_Text_NatureToDoWithStatGains: @ 820D9C1
# 14 "data/maps/SlateportCity_House/scripts.pory"
	.string "My Pokémon has a Hasty nature.\p"
# 15 "data/maps/SlateportCity_House/scripts.pory"
	.string "It has higher Speed compared to\n"
# 16 "data/maps/SlateportCity_House/scripts.pory"
	.string "my other Pokémon.\p"
# 17 "data/maps/SlateportCity_House/scripts.pory"
	.string "Maybe their nature has something to\n"
# 18 "data/maps/SlateportCity_House/scripts.pory"
	.string "do with the stat gains of Pokémon.$"
# 19 "data/maps/SlateportCity_House/scripts.pory"

# 20 "data/maps/SlateportCity_House/scripts.pory"
SlateportCity_House_Text_MustBeGoingToBattleTent: @ 820DA59
# 21 "data/maps/SlateportCity_House/scripts.pory"
	.string "You're a Trainer, aren't you?\p"
# 22 "data/maps/SlateportCity_House/scripts.pory"
	.string "Since you came to Slateport City,\n"
# 23 "data/maps/SlateportCity_House/scripts.pory"
	.string "you must be going to the Battle Tent.$"
