# 1 "data/maps/OneIsland_House1/scripts.pory"

# 2 "data/maps/OneIsland_House1/scripts.pory"
OneIsland_House1_MapScripts::
# 3 "data/maps/OneIsland_House1/scripts.pory"
	.byte 0
# 4 "data/maps/OneIsland_House1/scripts.pory"
	
# 5 "data/maps/OneIsland_House1/scripts.pory"
OneIsland_House1_EventScript_OldMan:: @ 817135C
# 6 "data/maps/OneIsland_House1/scripts.pory"
	msgbox OneIsland_House1_Text_GazeUponVolcanoOnSunnyDays, MSGBOX_NPC
# 7 "data/maps/OneIsland_House1/scripts.pory"
	end
# 8 "data/maps/OneIsland_House1/scripts.pory"

# 9 "data/maps/OneIsland_House1/scripts.pory"
OneIsland_House1_EventScript_OldWoman:: @ 8171365
# 10 "data/maps/OneIsland_House1/scripts.pory"
	msgbox OneIsland_House1_Text_LastTimeMtEmberErupted, MSGBOX_NPC
# 11 "data/maps/OneIsland_House1/scripts.pory"
	end
# 12 "data/maps/OneIsland_House1/scripts.pory"
	
# 13 "data/maps/OneIsland_House1/scripts.pory"
OneIsland_House1_Text_GazeUponVolcanoOnSunnyDays:: @ 81A2332
# 14 "data/maps/OneIsland_House1/scripts.pory"
    .string "On sunny days, I step out and gaze\n"
# 15 "data/maps/OneIsland_House1/scripts.pory"
    .string "upon the volcano.\p"
# 16 "data/maps/OneIsland_House1/scripts.pory"
    .string "That's my daily routine.$"
# 17 "data/maps/OneIsland_House1/scripts.pory"

# 18 "data/maps/OneIsland_House1/scripts.pory"
OneIsland_House1_Text_LastTimeMtEmberErupted:: @ 81A2380
# 19 "data/maps/OneIsland_House1/scripts.pory"
    .string "Let me think… When was the last\n"
# 20 "data/maps/OneIsland_House1/scripts.pory"
    .string "time MT. EMBER erupted?$"
