#ifndef GUARD_QUESTS_H
#define GUARD_QUESTS_H 

//#include constants/quests.h       //included in global.h

//#define FLAG_QUEST_MENU_ACTIVE    0x264 //added to constants/flags.h

#define NO_ACTIVE_QUEST             -1

#define ACHIEVEMENTS_TITLE_NAME_LENGTH  50
#define ACHIEVEMENTS_DESC_NAME_LENGTH   150
#define ACHIEVEMENTS_HINT_NAME_LENGTH   20
#define ACHIEVEMENTS_NUM_POSSIBLE_STEPS 5

#define REWARD_TYPE_ITEM	    0
#define REWARD_TYPE_OTHER	    1

#define REWARD_TYPE_FLAG_SET	0
#define REWARD_TYPE_FLAG_CLEAR  1
#define REWARD_TYPE_TRAINER_EXP	2
#define REWARD_TYPE_BP   	    3
#define REWARD_TYPE_MONEY   	4

struct Achievements 
{
    const u8 name[ACHIEVEMENTS_TITLE_NAME_LENGTH];
    const u8 desc[ACHIEVEMENTS_DESC_NAME_LENGTH];
    const u8 hint[ACHIEVEMENTS_HINT_NAME_LENGTH];
    const u8 rewardName[ACHIEVEMENTS_HINT_NAME_LENGTH];
	u8  rewardType;
	u16 reward;
	u16 reward_qty;
	u8  difficulty;
	u16 defeatedTrainer;
	u16 completedFlag;
	u16 completedVar;
    u16 varCompletedValue;
};

extern const struct Achievements sAchievementsData[MAX_ACHIEVEMENTS_NUM];

enum 
{
	QUEST_DIFFICULTY_EASY,
	QUEST_DIFFICULTY_MEDIUM,
	QUEST_DIFFICULTY_HARD,
	QUEST_DIFFICULTY_EXTREME,
	QUEST_DIFFICULTY_IMPOSSIBLE,
	QUEST_DIFFICULTY_DISABLED,
};

enum{
    ACHIEVEMENT_FIRST_BADGE,
    ACHIEVEMENT_FOURTH_BADGE,
    ACHIEVEMENT_EIGHT_BADGE,
    ACHIEVEMENT_FINAL_BADGE,
    ACHIEVEMENT_DEFEAT_WALLY,
    ACHIEVEMENT_DEFEAT_WALLACE,
    ACHIEVEMENT_DEFEAT_RAYQUAZA,
    ACHIEVEMENT_SEVII_1_COMPLETE,
    ACHIEVEMENT_SEVII_2_COMPLETE,
    ACHIEVEMENT_SEVII_3_COMPLETE,
    ACHIEVEMENT_SEVII_4_COMPLETE,
    ACHIEVEMENT_SEVII_5_COMPLETE,
    ACHIEVEMENT_SEVII_6_COMPLETE,
    ACHIEVEMENT_SEVII_7_COMPLETE,
    ACHIEVEMENT_SEVII_8_COMPLETE,
    ACHIEVEMENT_COMPLETE_TRADES,
    ACHIEVEMENT_COMPLETE_FOSSILS,
    ACHIEVEMENT_COMPLETE_MAX_HAPPINESS,
    ACHIEVEMENT_COMPLETE_150_EVOS,
	ACHIEVEMENT_VISIT_ALL_OF_HOENN,
    ACHIEVEMENT_VISIT_ALL_OF_SEVII,
    ACHIEVEMENT_COMPLETE_STEP_COUNT,
    ACHIEVEMENT_GET_777_20_TIMES,
    ACHIEVEMENT_GET_LOTTERY,
    ACHIEVEMENT_GET_6_GREEN_SHINIES,
    ACHIEVEMENT_GET_5_SHINIES,
    ACHIEVEMENT_PLANT_50_BERRIES,
    ACHIEVEMENT_USE_THE_DEXNAV_500_TIMES,
    ACHIEVEMENT_GET_RAINY_WEATHER_50_TIMES,
    ACHIEVEMENT_USE_THE_DAYCARE_50_TIMES,
    ACHIEVEMENT_USE_THE_CLOCK_75_TIMES,
    ACHIEVEMENT_WIN_25_POKEMON_CONTESTS,
    ACHIEVEMENT_CAPTURE_50_FISHED_MONS,
    ACHIEVEMENT_USE_THE_SAFARI_ZONE_50_TIMES,
    ACHIEVEMENT_USE_STRUGGLE_20_TIMES,
    ACHIEVEMENT_CATCH_75_MONS,
    ACHIEVEMENT_CATCH_150_MONS,
    ACHIEVEMENT_CATCH_500_MONS,
    ACHIEVEMENT_START_30_MOCK_BATTLES_NORMAL,
    ACHIEVEMENT_START_50_MOCK_BATTLES_HARD,
    ACHIEVEMENT_DO_2500_DAMAGE,
    ACHIEVEMENT_DO_7500_DAMAGE,
    ACHIEVEMENT_DO_12500_DAMAGE,
    ACHIEVEMENT_LOTERY_MATCH_1,
    ACHIEVEMENT_LOTERY_MATCH_2,
    ACHIEVEMENT_LOTERY_MATCH_3,
    ACHIEVEMENT_LOTERY_MATCH_4,
    ACHIEVEMENT_UPDATE_YOUR_GAME_5_TIMES,
    ACHIEVEMENT_YEAR_OLD_SAVE,
    ACHIEVEMENT_START_30_TRENDS,
    ACHIEVEMENT_MAKE_30_POKEBLOCKS,
    ACHIEVEMENT_COMPLETE_SCANNER_QUEST,
    ACHIEVEMENT_DEFEAT_RED_AND_STEVEN,
    ACHIEVEMENT_GET_SILVER_SYMBOLS,
    ACHIEVEMENT_GET_SHINY_TITLESCREEN,
    ACHIEVEMENT_GET_POKERUS,
    ACHIEVEMENT_START_NEW_GAME_PLUS,
    ACHIEVEMENT_START_MENU_AT_3AM,
	ACHIEVEMENT_WIN_MOCK_BATTLE_WITH_ONLY_METRONOME,
    ACHIEVEMENT_COMPLETE_TM_COLLECTION,
    ACHIEVEMENT_COMPLETE_GOLD_SYMBOLS,
    ACHIEVEMENT_COMPLETE_POKEDEX,
    ACHIEVEMENT_DEFEAT_ARCEUS,
    ACHIEVEMENT_COMPLETE_ALL_ACHIVEMENTS,
    NUM_ACHIEVEMENTS,
};

#define QUEST_STATUS_LOCKED          0
#define QUEST_STATUS_UNLOCKED        1
#define QUEST_STATUS_COMPLETED       253
#define QUEST_STATUS_REWARD_OBTAINED 254

enum QuestCases
{
    ACHIEVEMENTS_FLAG_GET_UNLOCKED,      // check if quest is unlocked
    ACHIEVEMENTS_FLAG_SET_UNLOCKED,      // mark unlocked quest
    ACHIEVEMENTS_FLAG_GET_COMPLETED,     // check if quest is completed
    ACHIEVEMENTS_FLAG_SET_COMPLETED,     // mark completed quest
    ACHIEVEMENTS_FLAG_GET_REWARDED,      // check if you got your reward
    ACHIEVEMENTS_FLAG_SET_REWARDED,      // mark as rewarded
};

// functions
void CreateItemMenuIcon(u16, u8);
void ResetItemMenuIconState(void);
void DestroyItemMenuIcon(u8 idx);
void Task_OpenQuestMenuFromStartMenu(u8);
bool8 GetSetQuestFlag(u8 quest, u8 caseId);
s8 GetActiveQuestIndex(void);
void SetActiveQuest(u8 questId);
void TextWindow_SetStdFrame0_WithPal(u8 windowId, u16 destOffset, u8 palIdx);
void QuestMenu_Init(u8 a0, MainCallback callback);
void SetQuestMenuActive(void);
void ResetActiveQuest(void);
void GetQuestName(u8 *dst, u8 questId);
void CopyQuestName(u8 *dst, u8 questId);
void ResetQuestFlags(void);

#endif // GUARD_QUESTS_H