# 1 "data/maps/OneIsland_House2/scripts.pory"

# 2 "data/maps/OneIsland_House2/scripts.pory"
OneIsland_House2_MapScripts::
# 3 "data/maps/OneIsland_House2/scripts.pory"
	.byte 0
# 4 "data/maps/OneIsland_House2/scripts.pory"

# 5 "data/maps/OneIsland_House2/scripts.pory"
OneIsland_House2_EventScript_Lass:: @ 817136F
# 6 "data/maps/OneIsland_House2/scripts.pory"
	msgbox OneIsland_House2_Text_IWantToStayHereForever, MSGBOX_NPC
# 7 "data/maps/OneIsland_House2/scripts.pory"
	end
# 8 "data/maps/OneIsland_House2/scripts.pory"
	
# 9 "data/maps/OneIsland_House2/scripts.pory"
OneIsland_House2_Text_IWantToStayHereForever:: @ 81A23B8
# 10 "data/maps/OneIsland_House2/scripts.pory"
    .string "Young people all want to go off to\n"
# 11 "data/maps/OneIsland_House2/scripts.pory"
    .string "big cities.\p"
# 12 "data/maps/OneIsland_House2/scripts.pory"
    .string "But I want to stay here forever!$"
