# 1 "data/maps/SouthernIsland_Exterior/scripts.pory"

# 2 "data/maps/SouthernIsland_Exterior/scripts.pory"
.set LOCALID_SAILOR, 1
# 3 "data/maps/SouthernIsland_Exterior/scripts.pory"
.set LOCALID_SS_TIDAL, 2
# 4 "data/maps/SouthernIsland_Exterior/scripts.pory"

# 5 "data/maps/SouthernIsland_Exterior/scripts.pory"
SouthernIsland_Exterior_MapScripts:: @ 82429C8
# 6 "data/maps/SouthernIsland_Exterior/scripts.pory"
	map_script MAP_SCRIPT_ON_TRANSITION, SouthernIsland_Exterior_OnTransition
# 7 "data/maps/SouthernIsland_Exterior/scripts.pory"
	.byte 0
# 8 "data/maps/SouthernIsland_Exterior/scripts.pory"

# 9 "data/maps/SouthernIsland_Exterior/scripts.pory"
SouthernIsland_Exterior_OnTransition: @ 82429CE
# 10 "data/maps/SouthernIsland_Exterior/scripts.pory"
	setflag FLAG_LANDMARK_SOUTHERN_ISLAND
# 11 "data/maps/SouthernIsland_Exterior/scripts.pory"
	end
# 12 "data/maps/SouthernIsland_Exterior/scripts.pory"

# 13 "data/maps/SouthernIsland_Exterior/scripts.pory"
SouthernIsland_Exterior_EventScript_Sailor:: @ 82429D2
# 14 "data/maps/SouthernIsland_Exterior/scripts.pory"
	lock
# 15 "data/maps/SouthernIsland_Exterior/scripts.pory"
	faceplayer
# 16 "data/maps/SouthernIsland_Exterior/scripts.pory"
	msgbox EventTicket_Text_SouthernIslandSailBack, MSGBOX_YESNO
# 17 "data/maps/SouthernIsland_Exterior/scripts.pory"
	compare VAR_RESULT, NO
# 18 "data/maps/SouthernIsland_Exterior/scripts.pory"
	goto_if_eq SouthernIsland_Exterior_EventScript_AsYouLike
# 19 "data/maps/SouthernIsland_Exterior/scripts.pory"
	msgbox EventTicket_Text_SailHome, MSGBOX_DEFAULT
# 20 "data/maps/SouthernIsland_Exterior/scripts.pory"
	closemessage
# 21 "data/maps/SouthernIsland_Exterior/scripts.pory"
	applymovement VAR_LAST_TALKED, Common_Movement_WalkInPlaceFastestDown
# 22 "data/maps/SouthernIsland_Exterior/scripts.pory"
	waitmovement 0
# 23 "data/maps/SouthernIsland_Exterior/scripts.pory"
	delay 30
# 24 "data/maps/SouthernIsland_Exterior/scripts.pory"
	hideobjectat LOCALID_SAILOR, MAP_SOUTHERN_ISLAND_EXTERIOR
# 25 "data/maps/SouthernIsland_Exterior/scripts.pory"
	setvar VAR_0x8004, LOCALID_SS_TIDAL
# 26 "data/maps/SouthernIsland_Exterior/scripts.pory"
	call Common_EventScript_FerryDepartIsland
# 27 "data/maps/SouthernIsland_Exterior/scripts.pory"
	warp MAP_LILYCOVE_CITY_HARBOR, 255, 8, 11
# 28 "data/maps/SouthernIsland_Exterior/scripts.pory"
	waitstate
# 29 "data/maps/SouthernIsland_Exterior/scripts.pory"
	release
# 30 "data/maps/SouthernIsland_Exterior/scripts.pory"
	end
# 31 "data/maps/SouthernIsland_Exterior/scripts.pory"

# 32 "data/maps/SouthernIsland_Exterior/scripts.pory"
SouthernIsland_Exterior_EventScript_AsYouLike:: @ 8242A17
# 33 "data/maps/SouthernIsland_Exterior/scripts.pory"
	msgbox EventTicket_Text_AsYouLike, MSGBOX_DEFAULT
# 34 "data/maps/SouthernIsland_Exterior/scripts.pory"
	release
# 35 "data/maps/SouthernIsland_Exterior/scripts.pory"
	end
# 36 "data/maps/SouthernIsland_Exterior/scripts.pory"

# 37 "data/maps/SouthernIsland_Exterior/scripts.pory"
Ferry_EventScript_DepartIslandSouth:: @ 8242A21
# 38 "data/maps/SouthernIsland_Exterior/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, Ferry_EventScript_DepartIslandBoardSouth
# 39 "data/maps/SouthernIsland_Exterior/scripts.pory"
	waitmovement 0
# 40 "data/maps/SouthernIsland_Exterior/scripts.pory"
	return
# 41 "data/maps/SouthernIsland_Exterior/scripts.pory"

# 42 "data/maps/SouthernIsland_Exterior/scripts.pory"
Ferry_EventScript_DepartIslandWest:: @ 8242A2C
# 43 "data/maps/SouthernIsland_Exterior/scripts.pory"
	applymovement OBJ_EVENT_ID_PLAYER, Ferry_EventScript_DepartIslandBoardWest
# 44 "data/maps/SouthernIsland_Exterior/scripts.pory"
	waitmovement 0
# 45 "data/maps/SouthernIsland_Exterior/scripts.pory"
	return
# 46 "data/maps/SouthernIsland_Exterior/scripts.pory"

# 47 "data/maps/SouthernIsland_Exterior/scripts.pory"
Ferry_EventScript_DepartIslandBoardSouth: @ 8242A37
# 48 "data/maps/SouthernIsland_Exterior/scripts.pory"
	walk_down
# 49 "data/maps/SouthernIsland_Exterior/scripts.pory"
	step_end
# 50 "data/maps/SouthernIsland_Exterior/scripts.pory"

# 51 "data/maps/SouthernIsland_Exterior/scripts.pory"
Ferry_EventScript_DepartIslandBoardWest: @ 8242A39
# 52 "data/maps/SouthernIsland_Exterior/scripts.pory"
	walk_left
# 53 "data/maps/SouthernIsland_Exterior/scripts.pory"
	walk_in_place_fastest_down
# 54 "data/maps/SouthernIsland_Exterior/scripts.pory"
	step_end
# 55 "data/maps/SouthernIsland_Exterior/scripts.pory"

# 56 "data/maps/SouthernIsland_Exterior/scripts.pory"
SouthernIsland_Exterior_EventScript_Sign:: @ 8242A3C
# 57 "data/maps/SouthernIsland_Exterior/scripts.pory"
	msgbox SouthernIsland_Exterior_Text_Sign, MSGBOX_SIGN
# 58 "data/maps/SouthernIsland_Exterior/scripts.pory"
	end
